DROP TABLE IF EXISTS `HB-01-ONE-TO-ONE`.REVIEW;

CREATE TABLE `HB-01-ONE-TO-ONE`.REVIEW (
	ID INT NOT NULL AUTO_INCREMENT,
    COMMENT VARCHAR(256) DEFAULT NULL,
    COURSE_ID INT  DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY KEY_COURSE_ID_IDX (COURSE_ID),
    CONSTRAINT FK_COURSE_REVIEW FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION
);