DROP DATABASE IF EXISTS PHARMACY;

CREATE DATABASE IF NOT EXISTS PHARMACY;

CREATE TABLE PHARMACY.TAX_CATEGORY (
    ID INT AUTO_INCREMENT,
    CODE VARCHAR(20) NOT NULL,
    CGST DECIMAL(5, 2) NOT NULL,
    IGST DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PHARMACY.CODE_VALUE (
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(5) NOT NULL,
    VALUE VARCHAR(50) NOT NULL,
    DOMAIN_NAME VARCHAR(50) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PHARMACY.PATIENT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) DEFAULT NULL,
	UHID INTEGER NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	EMAIL VARCHAR(40) DEFAULT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY (UHID)
);

CREATE TABLE IF NOT EXISTS PHARMACY.DRUG_SETUP (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    TYPE VARCHAR(5) NOT NULL,
    UNITS_PER_PACK DECIMAL(5, 2) DEFAULT 0.00,
    HSN_CODE VARCHAR(12) NOT NULL,
    CGST DECIMAL(5, 2)  DEFAULT 0.00,
	IGST DECIMAL(5, 2)  DEFAULT 0.00,
	SGST DECIMAL(5, 2)  DEFAULT 0.00,
	STATUS VARCHAR(1) NOT NULL,
    COMPOSITION VARCHAR(50) DEFAULT NULL,
	GENERIC_NAME VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PHARMACY.SUPPLIER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  CODE VARCHAR(5) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(20) DEFAULT NULL,
  ACCOUNT_HOLDER_NAME  VARCHAR(50) DEFAULT NULL,
  IFSC_CODE VARCHAR(20) DEFAULT NULL,
  TAX_NUMBER VARCHAR(15) DEFAULT NULL,
  LICENCE_NUMBER VARCHAR(15) DEFAULT NULL,
  EMAIL VARCHAR(30) DEFAULT NULL,
  PHONE_NUMBER VARCHAR(10) DEFAULT NULL,
  STATUS VARCHAR(2) NOT NULL,
  PRIMARY KEY(ID)
);