DROP DATABASE IF EXISTS PHARMACY;

CREATE DATABASE IF NOT EXISTS PHARMACY;

CREATE TABLE PHARMACY.TAX_CATEGORY (
    ID INT AUTO_INCREMENT,
    CODE VARCHAR(20) NOT NULL,
    CGST DECIMAL(5, 2) NOT NULL,
    IGST DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PHARMACY.CODE_VALUE (
    ID INT NOT NULL AUTO_INCREMENT,
    CODE VARCHAR(5) NOT NULL,
    VALUE VARCHAR(50) NOT NULL,
    DOMAIN_NAME VARCHAR(50) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PHARMACY.PATIENT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) DEFAULT NULL,
	UHID INTEGER NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER VARCHAR(1) NOT NULL,
	EMAIL VARCHAR(40) DEFAULT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY (UHID)
);

CREATE TABLE IF NOT EXISTS PHARMACY.DRUG_SETUP (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    TYPE VARCHAR(5) NOT NULL,
    UNITS_PER_PACK DECIMAL(5, 2) DEFAULT 0.00,
    HSN_CODE VARCHAR(12) NOT NULL,
    CGST DECIMAL(5, 2)  DEFAULT 0.00,
	IGST DECIMAL(5, 2)  DEFAULT 0.00,
	SGST DECIMAL(5, 2)  DEFAULT 0.00,
	STATUS VARCHAR(1) NOT NULL,
    COMPOSITION VARCHAR(50) DEFAULT NULL,
	GENERIC_NAME VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PHARMACY.SUPPLIER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  CODE VARCHAR(5) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(20) DEFAULT NULL,
  ACCOUNT_HOLDER_NAME  VARCHAR(50) DEFAULT NULL,
  IFSC_CODE VARCHAR(20) DEFAULT NULL,
  TAX_NUMBER VARCHAR(15) DEFAULT NULL,
  LICENCE_NUMBER VARCHAR(15) DEFAULT NULL,
  EMAIL VARCHAR(30) DEFAULT NULL,
  PHONE_NUMBER VARCHAR(10) DEFAULT NULL,
  STATUS VARCHAR(2) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE INDEX IND_SUPPLIER_CODE ON SUPPLIER(CODE);

CREATE TABLE PHARMACY.INVENTORY (
	ID INT NOT NULL AUTO_INCREMENT,
	SUPPLIER_CODE VARCHAR(5) NOT NULL,
	INVOICE_NUMBER VARCHAR(20) NOT NULL,
	INVOICE_DATE DATE NOT NULL,
	DISCOUNT_PERC DECIMAL(5,3) DEFAULT 0.00,  
	DISCOUNT_AMT DECIMAL(5,3) DEFAULT 0.00,
	INVOICE_AMT DECIMAL(8,3) DEFAULT 0.00,
	NOTES VARCHAR(100) DEFAULT NULL,
    INVENTORY_NUMBER INT NOT NULL,
    STATUS VARCHAR(3) NOT NULL,
    CREATED_BY VARCHAR(20) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
	PRIMARY KEY(ID),
	UNIQUE(INVENTORY_NUMBER),
    UNIQUE(INVOICE_NUMBER),
    CONSTRAINT FK_INV_SUPPLIER_CODE FOREIGN KEY (SUPPLIER_CODE) REFERENCES SUPPLIER(CODE)
);

CREATE TABLE PHARMACY.INVENTORY_DETAILS (
	ID INT NOT NULL AUTO_INCREMENT,
	DRUG_CODE INT NOT NULL,
	BATCH_NUMBER VARCHAR(20) NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	STRIP_SIZE INT DEFAULT 0.00,  
	QUANTITY INT NOT NULL,
	HSN_CODE VARCHAR(12) NOT NULL,
	CGST DECIMAL(8,3) DEFAULT 0.00,
	SGST DECIMAL(8,3) DEFAULT 0.00,
	MANUFACTURER_RATE DECIMAL(8,3) NOT NULL,
	TOTAL_MANUFACTURER_RATE DECIMAL(8,3) DEFAULT 0.00,
	NET_AMOUNT  DECIMAL(8,3) DEFAULT 0.00,
	INVOICE_AMOUNT  DECIMAL(8,3) DEFAULT 0.00,
	SELLING_COST DECIMAL(8,3) NOT NULL,
	TOTAL_SELLING_COST DECIMAL(8,3) DEFAULT 0.00,
	INVENTORY_DETAILS_ID INT NOT NULL,
	PRIMARY KEY(ID),
	CONSTRAINT FK_INVENTORY_DETAILS_ID FOREIGN KEY (INVENTORY_DETAILS_ID) REFERENCES INVENTORY(ID),
	CONSTRAINT FK_INV_DET_DRUG_CODE FOREIGN KEY (DRUG_CODE) REFERENCES DRUG_SETUP(ID)
);
