CREATE DATABASE IF NOT EXISTS `STUDENT_TRACKER`;

USE STUDENT_TRACKER;

DROP TABLE IF EXISTS `STUDENT`;

CREATE TABLE `STUDENT` (
	ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(45) DEFAULT NULL,
    LAST_NAME VARCHAR(45) DEFAULT NULL,
    EMAIL VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (ID)
);

SELECT * FROM STUDENT_TRACKER.STUDENT;