DROP TABLE IF EXISTS `HB-01-ONE-TO-ONE`.COURSE;

CREATE TABLE `HB-01-ONE-TO-ONE`.COURSE (
	ID INTEGER NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(128) DEFAULT NULL,
    INSTRUCTOR_ID INT DEFAULT NULL, 
    PRIMARY KEY(ID),
    UNIQUE KEY COURSE_TITLE_UNIQUE (TITLE),
    KEY FK_INSTRUCTOR_IDX (INSTRUCTOR_ID),
    CONSTRAINT FK_INSTRUCTOR FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION
);