DROP SCHEMA IF EXISTS `HB-01-ONE-TO-ONE`;

CREATE SCHEMA `HB-01-ONE-TO-ONE`;

USE `HB-01-ONE-TO-ONE`;

CREATE TABLE INSTRUCTOR_DETAIL (
	ID INT NOT NULL AUTO_INCREMENT,
    YOUTUBE_CHANNEL VARCHAR(128) DEFAULT NULL,
    HOBBY VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE INSTRUCTOR (
	ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(45) DEFAULT NULL,
    LAST_NAME VARCHAR(45) DEFAULT NULL,
    EMAIL VARCHAR(45) DEFAULT NULL,
    INSTRUCTOR_DETAIL_ID INT NOT NULL,
    PRIMARY KEY(ID),
    KEY FK_DETAIL_IDX (INSTRUCTOR_DETAIL_ID),
    CONSTRAINT INSTRUCTOR_DETAIL_FK FOREIGN KEY (INSTRUCTOR_DETAIL_ID) 
    REFERENCES INSTRUCTOR_DETAIL(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

SET FOREIGN_KEY_CHECKS = 1;